server:
  port: 3003
spring:
  data:
    mongodb:
      database: supplychainmanagement
      port: 27017
      host: localhost
  application:
    name: INVENTORY-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: "http://localhost:8761/eureka/"
      instance: localhost