server:
  port: 3004

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: supplychainmanagement
  application:
    name: ORDER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: "http://localhost:8761/eureka/"
      instance: localhost